package iti.jets.model;
// Generated Aug 24, 2024, 11:37:30 AM by Hibernate Tools 6.5.1.Final


import jakarta.persistence.*;

/**
 * Cart generated by hbm2java
 */
@Entity
@Table(name="cart"
    ,catalog="shomya"
)
public class Cart  implements java.io.Serializable {


     private CartId id;
     private User user;
     private Product product;
     private int quantity;
     private float currentPrice;

    public Cart() {
    }

    public Cart(CartId id, User user, Product product, int quantity, float currentPrice) {
       this.id = id;
       this.user = user;
       this.product = product;
       this.quantity = quantity;
       this.currentPrice = currentPrice;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="productId", column=@Column(name="product_id", nullable=false) ), 
        @AttributeOverride(name="userId", column=@Column(name="user_id", nullable=false) ) } )
    public CartId getId() {
        return this.id;
    }
    
    public void setId(CartId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false, insertable=false, updatable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="product_id", nullable=false, insertable=false, updatable=false)
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

    
    @Column(name="quantity", nullable=false)
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    
    @Column(name="current_price", nullable=false, precision=12)
    public float getCurrentPrice() {
        return this.currentPrice;
    }
    
    public void setCurrentPrice(float currentPrice) {
        this.currentPrice = currentPrice;
    }




}


