package iti.jets.model;
// Generated Aug 29, 2024, 10:26:43 PM by Hibernate Tools 6.5.1.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;

/**
 * CartItem generated by hbm2java
 */
@Entity
@Table(name="cart_item"
    ,catalog="shomya"
)
public class CartItem  implements java.io.Serializable {


     private int id;
     private Product product;
     private int quantity;
     private float currentPrice;
     private Set<Customer> customers = new HashSet<Customer>(0);
     private Set<Order> orders = new HashSet<Order>(0);

    public CartItem() {
    }

	
    public CartItem(int id, Product product, int quantity, float currentPrice) {
        this.id = id;
        this.product = product;
        this.quantity = quantity;
        this.currentPrice = currentPrice;
    }
    public CartItem(int id, Product product, int quantity, float currentPrice, Set<Customer> customers, Set<Order> orders) {
       this.id = id;
       this.product = product;
       this.quantity = quantity;
       this.currentPrice = currentPrice;
       this.customers = customers;
       this.orders = orders;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="product_id", nullable=false)
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

    
    @Column(name="quantity", nullable=false)
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    
    @Column(name="current_price", nullable=false, precision=12)
    public float getCurrentPrice() {
        return this.currentPrice;
    }
    
    public void setCurrentPrice(float currentPrice) {
        this.currentPrice = currentPrice;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="cart", catalog="shomya", joinColumns = { 
        @JoinColumn(name="cart_item_id", nullable=false) }, inverseJoinColumns = {
        @JoinColumn(name="customer_id", nullable=false) })
    public Set<Customer> getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Set<Customer> customers) {
        this.customers = customers;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="order_items", catalog="shomya", joinColumns = { 
        @JoinColumn(name="cart_item_id", nullable=false) }, inverseJoinColumns = {
        @JoinColumn(name="order_id", nullable=false) })
    public Set<Order> getOrders() {
        return this.orders;
    }
    
    public void setOrders(Set<Order> orders) {
        this.orders = orders;
    }




}


