package iti.jets.model;
// Generated Aug 24, 2024, 11:37:30 AM by Hibernate Tools 6.5.1.Final


import jakarta.persistence.*;

import java.util.HashSet;
import java.util.Set;

import static jakarta.persistence.GenerationType.IDENTITY;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name="category"
    ,catalog="shomya"
    , uniqueConstraints = @UniqueConstraint(columnNames="name") 
)
public class Category  implements java.io.Serializable {


     private int id;
     private String name;
     private Set<User> users = new HashSet<User>(0);
     private Set<Product> products = new HashSet<Product>(0);

    public Category() {
    }

	
    public Category(String name) {
        this.name = name;
    }
    public Category(int id, String name, Set<User> users, Set<Product> products) {
       this.id = id;
       this.name = name;
       this.users = users;
       this.products = products;
    }
   
     @Id@GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="name", unique=true, nullable=false, length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="user_intersts", catalog="shomya", joinColumns = { 
        @JoinColumn(name="category_id", nullable=false, updatable=true) }, inverseJoinColumns = {
        @JoinColumn(name="user_id", nullable=false, updatable=true) })
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="category_has_product", catalog="shomya", joinColumns = { 
        @JoinColumn(name="category_id", nullable=false, updatable=true) }, inverseJoinColumns = {
        @JoinColumn(name="product_id", nullable=false, updatable=true) })
    public Set<Product> getProducts() {
        return this.products;
    }
    
    public void setProducts(Set<Product> products) {
        this.products = products;
    }




}


