package iti.jets.model;
// Generated Aug 29, 2024, 10:26:43 PM by Hibernate Tools 6.5.1.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Order generated by hbm2java
 */
@Entity
@Table(name="order"
    ,catalog="shomya"
)
public class Order  implements java.io.Serializable {


     private int id;
     private Customer customer;
     private float totalPrice;
     private Timestamp orderDate;
     private Set<CartItem> cartItems = new HashSet<CartItem>(0);

    public Order() {
    }

	
    public Order(int id, Customer customer, Timestamp orderDate) {
        this.id = id;
        this.customer = customer;
        this.orderDate = orderDate;
    }
    public Order(int id, Customer customer, Timestamp orderDate, Set<CartItem> cartItems) {
       this.id = id;
       this.customer = customer;
       this.orderDate = orderDate;
       this.cartItems = cartItems;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    @Column(name="total_price", nullable=false, precision=12)
    public float getTotalPrice() {
        return this.totalPrice;
    }

    public void setTotalPrice(float price) {
        this.totalPrice = price;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="customer_id", nullable=false)
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="order_date", nullable=false, length=19)
    public Timestamp getOrderDate() {
        return this.orderDate;
    }
    
    public void setOrderDate(Timestamp orderDate) {
        this.orderDate = orderDate;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="order_items", catalog="shomya", joinColumns = { 
        @JoinColumn(name="order_id", nullable=false) }, inverseJoinColumns = {
        @JoinColumn(name="cart_item_id", nullable=false) })
    public Set<CartItem> getCartItems() {
        return this.cartItems;
    }
    
    public void setCartItems(Set<CartItem> cartItems) {
        this.cartItems = cartItems;
    }




}


