package iti.jets.model;
// Generated Aug 29, 2024, 10:26:43 PM by Hibernate Tools 6.5.1.Final


import jakarta.persistence.*;

import static jakarta.persistence.GenerationType.IDENTITY;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
    ,catalog="shomya"
)
@Inheritance(strategy = InheritanceType.JOINED)
public abstract class User {


     private Integer id;
     protected String name;
     protected String username;
     protected String password;
     protected String email;

   
     @Id @GeneratedValue(strategy=IDENTITY)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="username", nullable=false, length=45)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="password", nullable=false, length=45)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="email", nullable=false, length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


