package iti.jets.dao;
// Generated Aug 24, 2024, 11:37:30 AM by Hibernate Tools 6.5.1.Final


import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * CartId generated by hbm2java
 */
@Embeddable
public class CartId  implements java.io.Serializable {


     private int productId;
     private int userId;

    public CartId() {
    }

    public CartId(int productId, int userId) {
       this.productId = productId;
       this.userId = userId;
    }
   


    @Column(name="product_id", nullable=false)
    public int getProductId() {
        return this.productId;
    }
    
    public void setProductId(int productId) {
        this.productId = productId;
    }


    @Column(name="user_id", nullable=false)
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CartId) ) return false;
		 CartId castOther = ( CartId ) other; 
         
		 return (this.getProductId()==castOther.getProductId())
 && (this.getUserId()==castOther.getUserId());
   }
   
   public int hashCode() {
         int result = 17;
         
        result = 37 * result + this.getProductId();
        result = 37 * result + this.getUserId();
         return result;
   }   


}


