package iti.jets.dao;
// Generated Aug 24, 2024, 11:37:30 AM by Hibernate Tools 6.5.1.Final


import jakarta.persistence.*;

import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name="product"
    ,catalog="shomya"
)
public class Product  implements java.io.Serializable {


     private int id;
     private String name;
     private float price;
     private int quantity;
     private Set<Category> categories = new HashSet<Category>(0);
     private Set<Cart> carts = new HashSet<Cart>(0);
     private Set<OrderHasProducts> orderHasProductses = new HashSet<OrderHasProducts>(0);

    public Product() {
    }

	
    public Product(int id, String name, float price, int quantity) {
        this.id = id;
        this.name = name;
        this.price = price;
        this.quantity = quantity;
    }
    public Product(int id, String name, float price, int quantity, Set<Category> categories, Set<Cart> carts, Set<OrderHasProducts> orderHasProductses) {
       this.id = id;
       this.name = name;
       this.price = price;
       this.quantity = quantity;
       this.categories = categories;
       this.carts = carts;
       this.orderHasProductses = orderHasProductses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="price", nullable=false, precision=12)
    public float getPrice() {
        return this.price;
    }
    
    public void setPrice(float price) {
        this.price = price;
    }

    
    @Column(name="quantity", nullable=false)
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="category_has_product", catalog="shomya", joinColumns = { 
        @JoinColumn(name="product_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="category_id", nullable=false, updatable=false) })
    public Set<Category> getCategories() {
        return this.categories;
    }
    
    public void setCategories(Set<Category> categories) {
        this.categories = categories;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="product")
    public Set<Cart> getCarts() {
        return this.carts;
    }
    
    public void setCarts(Set<Cart> carts) {
        this.carts = carts;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="product")
    public Set<OrderHasProducts> getOrderHasProductses() {
        return this.orderHasProductses;
    }
    
    public void setOrderHasProductses(Set<OrderHasProducts> orderHasProductses) {
        this.orderHasProductses = orderHasProductses;
    }




}


